/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#pragma mark -

/*
 * File: /Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/iPhoneSimulatorRemoteClient.framework/Versions/A/iPhoneSimulatorRemoteClient
 * UUID: 172EABBF-8E76-3313-AC9C-7B8CDF2A3DFD
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 12.0.0, Compatibility version: 1.0.0
 *
 *       Objective-C Garbage Collection: Supported
 *       Run path: @loader_path/../../../../../../../../Library/PrivateFrameworks/
 *               = /Developer/Library/PrivateFrameworks
 */

@class DTiPhoneSimulatorSessionConfig;

@protocol DTiPhoneSimulatorSessionDelegate
- (void)session:(id)arg1 didEndWithError:(id)arg2;
- (void)session:(id)arg1 didStart:(BOOL)arg2 withError:(id)arg3;
@end

@interface DTiPhoneSimulatorSession : NSObject
{
    NSString *_uuid;
    id <DTiPhoneSimulatorSessionDelegate> _delegate;
    NSNumber *_simulatedApplicationPID;
    long long _sessionLifecycleProgress;
    NSTimer *_timeoutTimer;
    DTiPhoneSimulatorSessionConfig *_sessionConfig;
    struct ProcessSerialNumber _simulatorPSN;
}

- (id)init;
- (void)dealloc;
- (id)description;
- (BOOL)requestStartWithConfig:(id)arg1 timeout:(double)arg2 error:(id *)arg3;
- (void)requestEndWithTimeout:(double)arg1;
- (void)_timeoutElapsed:(id)arg1;
- (void)_handleSimulatorReadyMessage:(id)arg1;
- (void)_handleSessionStartedInSimulator:(id)arg1;
- (void)_handleSessionEndedInSimulator:(id)arg1;
- (void)_activateSimulatorIfNeeded;
- (BOOL)_launchSimulatorApplicationGivingError:(id *)arg1;
- (BOOL)_startSessionInSimulatorWithError:(id *)arg1;
- (BOOL)_fillSessionStartRequestInfo:(id)arg1 fromConfig:(id)arg2 withError:(id *)arg3;
- (void)_callDelegateResponseFromSessionStartedInfo:(id)arg1;
- (void)_callDelegateResponseFromSessionEndedInfo:(id)arg1;
- (void)_endSimulatorSession;
- (id)_invalidConfigError;
@property(copy, nonatomic) DTiPhoneSimulatorSessionConfig *sessionConfig; // @synthesize sessionConfig=_sessionConfig;
@property(retain, nonatomic) NSTimer *timeoutTimer; // @synthesize timeoutTimer=_timeoutTimer;
@property(nonatomic) long long sessionLifecycleProgress; // @synthesize sessionLifecycleProgress=_sessionLifecycleProgress;
@property(copy, nonatomic) NSNumber *simulatedApplicationPID; // @synthesize simulatedApplicationPID=_simulatedApplicationPID;
@property(nonatomic, weak) id <DTiPhoneSimulatorSessionDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;

@end

@interface DTiPhoneSimulatorApplicationSpecifier : NSObject <NSCopying>
{
    NSString *appPath;
    NSString *bundleID;
}

+ (id)specifierWithApplicationPath:(id)arg1;
+ (id)specifierWithApplicationBundleIdentifier:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
@property(copy, nonatomic) NSString *bundleID; // @synthesize bundleID;
@property(copy, nonatomic) NSString *appPath; // @synthesize appPath;

@end

@interface DTiPhoneSimulatorSystemRoot : NSObject <NSCopying>
{
    NSString *sdkRootPath;
    NSString *sdkVersion;
    NSString *sdkDisplayName;
}

+ (id)defaultRoot;
+ (id)rootWithSDKPath:(id)arg1;
+ (id)rootWithSDKVersion:(id)arg1;
+ (id)knownRoots;
- (id)initWithSDKPath:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
@property(copy) NSString *sdkDisplayName; // @synthesize sdkDisplayName;
@property(copy) NSString *sdkVersion; // @synthesize sdkVersion;
@property(copy) NSString *sdkRootPath; // @synthesize sdkRootPath;

@end

@interface DTiPhoneSimulatorSessionConfig : NSObject <NSCopying>
{
    NSString *_localizedClientName;
    DTiPhoneSimulatorSystemRoot *_simulatedSystemRoot;
    NSNumber *_simulatedDeviceFamily;
    DTiPhoneSimulatorApplicationSpecifier *_applicationToSimulateOnStart;
    NSArray *_simulatedApplicationLaunchArgs;
    NSDictionary *_simulatedApplicationLaunchEnvironment;
    BOOL _simulatedApplicationShouldWaitForDebugger;
    NSString *_simulatedApplicationStdOutPath;
    NSString *_simulatedApplicationStdErrPath;
}

+ (id)displayNameForDeviceFamily:(id)arg1;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
@property(copy) NSString *simulatedApplicationStdErrPath; // @synthesize simulatedApplicationStdErrPath=_simulatedApplicationStdErrPath;
@property(copy) NSString *simulatedApplicationStdOutPath; // @synthesize simulatedApplicationStdOutPath=_simulatedApplicationStdOutPath;
@property BOOL simulatedApplicationShouldWaitForDebugger; // @synthesize simulatedApplicationShouldWaitForDebugger=_simulatedApplicationShouldWaitForDebugger;
@property(copy) NSDictionary *simulatedApplicationLaunchEnvironment; // @synthesize simulatedApplicationLaunchEnvironment=_simulatedApplicationLaunchEnvironment;
@property(copy) NSArray *simulatedApplicationLaunchArgs; // @synthesize simulatedApplicationLaunchArgs=_simulatedApplicationLaunchArgs;
@property(copy) DTiPhoneSimulatorApplicationSpecifier *applicationToSimulateOnStart; // @synthesize applicationToSimulateOnStart=_applicationToSimulateOnStart;
@property(copy) NSNumber *simulatedDeviceFamily; // @synthesize simulatedDeviceFamily=_simulatedDeviceFamily;
@property(copy) DTiPhoneSimulatorSystemRoot *simulatedSystemRoot; // @synthesize simulatedSystemRoot=_simulatedSystemRoot;
@property(copy) NSString *localizedClientName; // @synthesize localizedClientName=_localizedClientName;

@end

